# Generated by Django 4.0.1 on 2022-12-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount_card', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('desc', models.CharField(max_length=1023, null=True)),
                ('bonuses', models.IntegerField()),
                ('tester_flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('flat', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('rent_price_month', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_ts', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.IntegerField()),
                ('bonuses_used', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.client')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.employee')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.flat')),
                ('order_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.orderstatus')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.flattype'),
        ),
    ]
